site_name: revision-notes
site_description: Interview Revision Notes for Software Engineering
site_author: Samarth D Suryavamshi
site_url: https://samarth-d-suryavamshi.github.io/revision-notes/

repo_url: https://github.com/samarth-d-suryavamshi/revision-notes
repo_name: revision-notes

theme:
  name: material

  language: en

  favicon: assets/images/favicon.png
  logo: assets/images/logo.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer

    - navigation.indexes

    - navigation.path

    - content.action.edit

    - content.action.view

    - content.code.copy
    - content.code.select
    - content.code.annotate

    - content.tabs.link

    - search.highlight
    - search.suggest
    - search.share

    - toc.follow

    - announce.dismiss

  palette:

    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode

markdown_extensions:

  - admonition

  - attr_list

  - md_in_html

  - tables

  - footnotes

  - def_list

  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.escapeall

  - toc:
      permalink: true

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.emoji

  - pymdownx.keys

  - pymdownx.mark

  - pymdownx.tilde

  - pymdownx.caret

plugins:

  - search

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/config.js
  - assets/js/search.js
  - assets/js/progress.js
  - assets/js/animations.js
  - assets/js/clipboard.js
  - assets/js/extra.js

nav:

  - Home: 

      - Overview: index.md

      - Roadmap: roadmap.md

      - Interview prep:  interview-preparation.md

      - DSA: computer-science/dsa.md

      - System Design: computer-science/system-design.md

      - Databases: computer-science/databases.md

      - Programming: programming/language-specific.md

  - Roadmap: roadmap.md

  - Interview Preparation: interview-preparation.md

  - Computer Science:

      - Overview: computer-science/index.md

      - Mathematics: computer-science/mathematics.md

      - Data Structures & Algorithms: computer-science/dsa.md

      - Object-Oriented Programming: computer-science/oop.md

      - Computer Networks: computer-science/computer-networks.md

      - Operating Systems: computer-science/operating-systems.md

      - Databases: computer-science/databases.md

      - Git: computer-science/git.md

      - Linux: computer-science/linux.md
      
      - Backend Fundamentals: computer-science/backend-fundamentals.md

      - Software Engineering: computer-science/software-engineering.md

      - Object-Oriented Design: computer-science/object-oriented-design.md

      - Design Patterns: computer-science/design-patterns.md
      
      - Concurrency: computer-science/concurrency.md
      
      - Cloud Computing: computer-science/cloud.md

      - System Design: computer-science/system-design.md

      - Distributed Systems: computer-science/distributed-systems.md
      
  - Programming:

      - Overview: programming/index.md

      - Programming Fundamentals: programming/programming-fundamentals.md

      - Language Specific: programming/language-specific.md

      - The Developer's Mindset: programming/the-developer-mindset.md

  - Data:

      - Overview: data/index.md

      - Data Analytics: data/data-analytics.md

      - AI • ML • DL: data/ai-ml-dl.md

      - The Power of Data: data/the-power-of-data.md


  - Resources: resources.md

  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samarth-d-suryavamshi

# -----------------------------------------------------------------------------
# Copyright
# -----------------------------------------------------------------------------

copyright: >
  Copyright &copy; 2026 Samarth D Suryavamshi.
  <br>
  All Rights Reserved.<a href="license/">License</a>.